/**
 * Independent numeric verification of the sequences lessons (geometric sequences only — 2026 מיקוד).
 * Every answer is recomputed by generating the sequence term by term (repeated multiplication, iterating the
 * recursion rule, year-by-year / dose-by-dose / bounce-by-bounce simulation) and summing in a loop — never with the
 * closed-form S_n or S = a1/(1-q) formulas used in the solutions. Infinite sums are long truncations (4000 terms;
 * every convergent ratio here has |q| <= 0.95 inside the search ranges, so the neglected tail is below 1e-80).
 * Unknown parameters (q, x, k, number of terms) are found numerically — findRoots on the defining condition of the
 * statement, with a1 obtained by scaling a sequence that starts at 1 — or by brute force over n, and the resulting
 * model is checked against every given of the statement.
 */
import { describe, expect, it } from 'vitest';
import { findRoots } from '../../problems/verify';
import { sequencesContent } from './sequences';

const ex = (id: string) => Object.values(sequencesContent).flatMap((lesson) => lesson.exercises).find((e) => e.id === id)!;

/** Compares the authored answers (in order) with independently computed values, to `digits` relative digits. */
function expectAnswers(id: string, computed: number[], digits = 8) {
  const answers = ex(id).answers ?? [];
  expect(answers.length, `${id}: number of answers`).toBe(computed.length);
  answers.forEach((answer, index) => {
    const scale = Math.max(1, Math.abs(computed[index]));
    expect(answer.value / scale, `${id}: ${answer.label}`).toBeCloseTo(computed[index] / scale, digits);
  });
}

const LONG = 4000;

/** The first n terms a1, a1·q, a1·q², … generated by repeated multiplication. */
function terms(a1: number, q: number, n: number): number[] {
  const out: number[] = [];
  let current = a1;
  for (let i = 0; i < n; i += 1) {
    out.push(current);
    current *= q;
  }
  return out;
}

/** The first n terms of the sequence defined by a1 and the recursion rule a_{n+1} = rule(a_n). */
function iterate(a1: number, rule: (value: number) => number, n: number): number[] {
  const out: number[] = [];
  let current = a1;
  for (let i = 0; i < n; i += 1) {
    out.push(current);
    current = rule(current);
  }
  return out;
}

function sum(values: number[]): number {
  return values.reduce((total, value) => total + value, 0);
}

/** Truncated infinite sum (4000 terms). */
function infiniteSum(a1: number, q: number): number {
  return sum(terms(a1, q, LONG));
}

/** Terms in odd places a1, a3, a5, … and in even places a2, a4, … */
const oddPlaces = (values: number[]) => values.filter((_, index) => index % 2 === 0);
const evenPlaces = (values: number[]) => values.filter((_, index) => index % 2 === 1);

/** Asserts that consecutive ratios are all equal and returns that ratio. */
function commonRatio(values: number[]): number {
  const ratio = values[1] / values[0];
  for (let i = 1; i < values.length; i += 1) expect(values[i] / values[i - 1]).toBeCloseTo(ratio, 9);
  return ratio;
}

/** Roots of f on [lo, hi] with a small neighbourhood of 0 removed (q = 0 is never a ratio of a geometric sequence). */
function rootsAwayFromZero(f: (q: number) => number, lo: number, hi: number, steps = 4000): number[] {
  const negative = lo < 0 ? findRoots(f, lo, Math.min(hi, -1e-3), steps) : [];
  const positive = hi > 0 ? findRoots(f, Math.max(lo, 1e-3), hi, steps) : [];
  return [...negative, ...positive];
}

/** x-values for which three expressions form three consecutive terms of a geometric sequence (equal ratios). */
function geometricTripleRoots(f1: (x: number) => number, f2: (x: number) => number, f3: (x: number) => number, lo: number, hi: number): number[] {
  const gap = (x: number) => f2(x) / f1(x) - f3(x) / f2(x);
  // Sign changes at the poles of the ratios are discarded: only true zeros of the gap remain.
  return findRoots(gap, lo, hi).filter((x) => Math.abs(gap(x)) < 1e-6);
}

/** Smallest n >= 1 with predicate(n). */
function firstIndex(predicate: (n: number) => boolean, max = 10000): number {
  for (let n = 1; n <= max; n += 1) if (predicate(n)) return n;
  throw new Error('no index found');
}

const isIncreasing = (values: number[]) => values.every((value, index) => index === 0 || value > values[index - 1]);

describe('sequences lessons — answers verified by generating the sequences', () => {
  // ───────────── seq-geometric-intro ─────────────
  it('seq-geometric-intro-1', () => {
    const t = terms(-4, 0.5, 7);
    expect(t.slice(0, 4)).toEqual([-4, -2, -1, -0.5]);
    expect(isIncreasing(t)).toBe(true);
    expectAnswers('seq-geometric-intro-1', [t[6]]);
  });

  it('seq-geometric-intro-2', () => {
    const given = [48, -24, 12, -6];
    const q = commonRatio(given);
    const t = terms(48, q, 9);
    expect(t.slice(0, 4)).toEqual(given);
    expectAnswers('seq-geometric-intro-2', [q, t[8]]);
  });

  it('seq-geometric-intro-3', () => {
    const a1Of = (q: number) => -6 / terms(1, q, 2)[1];
    const qs = rootsAwayFromZero((q) => terms(a1Of(q), q, 5)[4] - 162, -10, 10);
    expect(qs).toHaveLength(1);
    const q = qs[0];
    const t = terms(a1Of(q), q, 6);
    expect(t[1]).toBeCloseTo(-6, 9);
    expect(t[4]).toBeCloseTo(162, 8);
    expect(t.every((value, index) => index === 0 || Math.sign(value) !== Math.sign(t[index - 1]))).toBe(true);
    expectAnswers('seq-geometric-intro-3', [t[0], q]);
  });

  it('seq-geometric-intro-4', () => {
    const a1Of = (q: number) => 40 / terms(1, q, 4)[3];
    const qs = rootsAwayFromZero((q) => terms(a1Of(q), q, 6)[5] - 10, -10, 10);
    expect(qs).toHaveLength(2);
    const [qNegative, qPositive] = qs;
    for (const q of qs) {
      const t = terms(a1Of(q), q, 6);
      expect(t[3]).toBeCloseTo(40, 9);
      expect(t[5]).toBeCloseTo(10, 9);
    }
    expect(qPositive).toBeCloseTo(0.5, 10);
    expectAnswers('seq-geometric-intro-4', [a1Of(qPositive), a1Of(qNegative)]);
  });

  it('seq-geometric-intro-5', () => {
    const qs = rootsAwayFromZero((q) => terms(5, q, 4)[3] - 40, -10, 10);
    expect(qs).toHaveLength(1);
    const t = terms(5, qs[0], 30);
    const n = t.findIndex((value) => Math.abs(value - 1280) < 1e-6) + 1;
    expect(n).toBeGreaterThan(0);
    expect(t.some((value) => Math.abs(value - 2000) < 1e-6)).toBe(false);
    expect(t[29]).toBeGreaterThan(2000);
    expectAnswers('seq-geometric-intro-5', [n]);
  });

  it('seq-geometric-intro-6', () => {
    const qs = rootsAwayFromZero((q) => terms(0.25, q, 9)[8] - 64, -10, 10);
    expect(qs).toHaveLength(2);
    const [qNegative, qPositive] = qs;
    const middles = qs.map((q) => terms(0.25, q, 9)[4]);
    expect(middles[0]).toBeCloseTo(middles[1], 9);
    expectAnswers('seq-geometric-intro-6', [qPositive, qNegative, middles[1]]);
  });

  it('seq-geometric-intro-7', () => {
    const second = (x: number) => x - 2;
    const third = (x: number) => x + 4;
    const fourth = (x: number) => 5 * x + 2;
    const xs = geometricTripleRoots(second, third, fourth, -50, 50);
    expect(xs).toHaveLength(2);
    const models = xs.map((x) => {
      const q = third(x) / second(x);
      const a1 = second(x) / q;
      return { x, q, a1, t: terms(a1, q, 8) };
    });
    const increasing = models.filter((model) => isIncreasing(model.t));
    expect(increasing).toHaveLength(1);
    const { x, q, a1, t } = increasing[0];
    expect(t[1]).toBeCloseTo(second(x), 9);
    expect(t[2]).toBeCloseTo(third(x), 9);
    expect(t[3]).toBeCloseTo(fourth(x), 9);
    expectAnswers('seq-geometric-intro-7', [x, q, a1]);
  });

  it('seq-geometric-intro-8', () => {
    // Positive terms: q > 0 and a1 > 0 with a1² · q⁴ = 144, where q⁴ is the fifth term of the sequence starting at 1.
    const a1Of = (q: number) => Math.sqrt(144 / terms(1, q, 5)[4]);
    const qs = findRoots((q) => {
      const t = terms(a1Of(q), q, 5);
      return t[1] + t[3] - 30;
    }, 0.01, 20);
    expect(qs).toHaveLength(2);
    const [qSmall, qLarge] = qs;
    for (const q of qs) {
      const t = terms(a1Of(q), q, 5);
      expect(t[0] * t[4]).toBeCloseTo(144, 8);
      expect(t[1] + t[3]).toBeCloseTo(30, 8);
    }
    expect(qLarge).toBeCloseTo(2, 9);
    expectAnswers('seq-geometric-intro-8', [a1Of(qLarge), a1Of(qSmall)]);
  });

  // ───────────── seq-geometric-sum ─────────────
  it('seq-geometric-sum-1', () => {
    expectAnswers('seq-geometric-sum-1', [sum(terms(5, 2, 7))]);
  });

  it('seq-geometric-sum-2', () => {
    const t: number[] = [];
    for (let value = 1; value <= 729; value *= 3) t.push(value);
    expect(t[t.length - 1]).toBe(729);
    expectAnswers('seq-geometric-sum-2', [t.length, sum(t)]);
  });

  it('seq-geometric-sum-3', () => {
    expectAnswers('seq-geometric-sum-3', [sum(terms(64, -0.5, 6))]);
  });

  it('seq-geometric-sum-4', () => {
    const n = firstIndex((k) => sum(terms(2, 3, k)) >= 728);
    expect(sum(terms(2, 3, n))).toBe(728);
    expectAnswers('seq-geometric-sum-4', [n]);
  });

  it('seq-geometric-sum-5', () => {
    const a1Of = (q: number) => 9 / sum(terms(1, q, 2));
    const f = (q: number) => sum(terms(a1Of(q), q, 4)) - 45;
    const qs = [...findRoots(f, -10, -1.01), ...findRoots(f, -0.99, 10)];
    expect(qs).toHaveLength(2);
    const [qNegative, qPositive] = qs;
    for (const q of qs) {
      expect(sum(terms(a1Of(q), q, 2))).toBeCloseTo(9, 9);
      expect(sum(terms(a1Of(q), q, 4))).toBeCloseTo(45, 8);
    }
    expect(qPositive).toBeCloseTo(2, 9);
    expectAnswers('seq-geometric-sum-5', [a1Of(qPositive), a1Of(qNegative)]);
  });

  it('seq-geometric-sum-6', () => {
    const t = terms(1, 2, 10);
    expectAnswers('seq-geometric-sum-6', [sum(oddPlaces(t)), sum(evenPlaces(t))]);
  });

  it('seq-geometric-sum-7', () => {
    const a1Of = (q: number) => 6 / terms(1, q, 2)[1];
    const qs = rootsAwayFromZero((q) => terms(a1Of(q), q, 5)[4] - 48, -10, 10);
    expect(qs).toHaveLength(1);
    const q = qs[0];
    const a1 = a1Of(q);
    const n = firstIndex((k) => sum(terms(a1, q, k)) > 1000);
    expect(sum(terms(a1, q, n - 1))).toBeLessThanOrEqual(1000);
    expectAnswers('seq-geometric-sum-7', [n]);
  });

  it('seq-geometric-sum-8', () => {
    const found: Array<{ n: number; q: number }> = [];
    for (let n = 2; n <= 40; n += 1) {
      for (const q of rootsAwayFromZero((r) => terms(1, r, n)[n - 1] - 512, -20, 20)) {
        if (Math.abs(sum(terms(1, q, n)) - 1023) < 1e-6) found.push({ n, q });
      }
    }
    expect(found).toHaveLength(1);
    expectAnswers('seq-geometric-sum-8', [found[0].q, found[0].n]);
  });

  // ───────────── seq-geometric-review ─────────────
  it('seq-geometric-review-1', () => {
    const a1Of = (q: number) => {
      const t = terms(1, q, 3);
      return 20 / (t[0] + t[2]);
    };
    const qs = findRoots((q) => {
      const t = terms(a1Of(q), q, 5);
      return t[4] - 4 * t[2];
    }, 0.01, 10);
    expect(qs).toHaveLength(1);
    const q = qs[0];
    const a1 = a1Of(q);
    const n = firstIndex((k) => sum(terms(a1, q, k)) >= 1020 - 1e-6);
    expect(sum(terms(a1, q, n))).toBeCloseTo(1020, 6);
    expectAnswers('seq-geometric-review-1', [a1, q, n]);
  });

  it('seq-geometric-review-2', () => {
    const a1Of = (q: number) => 12 / sum(terms(1, q, 2));
    const qs = findRoots((q) => {
      const t = terms(a1Of(q), q, 4);
      return t[2] + t[3] - 108;
    }, 0.01, 20);
    expect(qs).toHaveLength(1);
    const q = qs[0];
    const a1 = a1Of(q);
    const t = terms(a1, q, 20);
    expect(t.every((value) => value > 0)).toBe(true);
    const n = t.findIndex((value) => Math.abs(value - 2187) < 1e-6) + 1;
    expect(n).toBeGreaterThan(0);
    expectAnswers('seq-geometric-review-2', [a1, q, sum(t.slice(0, 6)), n]);
  });

  it('seq-geometric-review-3', () => {
    const xs = geometricTripleRoots((x) => x, (x) => x + 6, (x) => 4 * x, -50, 50);
    expect(xs).toHaveLength(2);
    const sums = new Map<number, number>();
    for (const x of xs) {
      const q = (x + 6) / x;
      const t = terms(x, q, 6);
      expect(t[2]).toBeCloseTo(4 * x, 9);
      sums.set(Math.round(x), sum(t));
    }
    expectAnswers('seq-geometric-review-3', [sums.get(6)!, sums.get(-2)!]);
  });

  it('seq-geometric-review-4', () => {
    const found: Array<{ k: number; q: number }> = [];
    for (let k = 1; k <= 15; k += 1) {
      const oddSum = (q: number) => sum(oddPlaces(terms(1, q, 2 * k)));
      for (const q of rootsAwayFromZero((r) => oddSum(r) - 85, -20, 20)) {
        if (Math.abs(sum(evenPlaces(terms(1, q, 2 * k))) - 170) < 1e-6) found.push({ k, q });
      }
    }
    expect(found).toHaveLength(1);
    expectAnswers('seq-geometric-review-4', [found[0].q, 2 * found[0].k]);
  });

  it('seq-geometric-review-5', () => {
    const found: Array<{ n: number; q: number }> = [];
    for (let n = 3; n <= 40; n += 1) {
      for (const q of rootsAwayFromZero((r) => terms(3, r, n)[n - 1] - 192, -20, 20)) {
        if (Math.abs(sum(terms(3, q, n)) - 381) < 1e-6) found.push({ n, q });
      }
    }
    expect(found).toHaveLength(1);
    expectAnswers('seq-geometric-review-5', [found[0].q, found[0].n - 2]);
  });

  it('seq-geometric-review-6', () => {
    const a1Of = (q: number) => 13 / sum(terms(1, q, 3));
    const qs = findRoots((q) => sum(terms(a1Of(q), q, 6).slice(3)) - 351, -10, 10);
    expect(qs).toHaveLength(1);
    const q = qs[0];
    const a1 = a1Of(q);
    const t = terms(a1, q, 9);
    expect(sum(t.slice(0, 3))).toBeCloseTo(13, 9);
    expect(sum(t.slice(3, 6))).toBeCloseTo(351, 8);
    expectAnswers('seq-geometric-review-6', [q, a1, sum(t.slice(6, 9)), sum(t)]);
  });

  // ───────────── seq-geometric-advanced ─────────────
  it('seq-geometric-advanced-1', () => {
    const a = Array.from({ length: 12 }, (_, index) => 3 * 2 ** index);
    const b = a.map((value) => value * value);
    expectAnswers('seq-geometric-advanced-1', [b[0], commonRatio(b)]);
  });

  it('seq-geometric-advanced-2', () => {
    const b = terms(2, 3, 10).map((value) => 1 / value);
    expectAnswers('seq-geometric-advanced-2', [commonRatio(b), b[3]]);
  });

  it('seq-geometric-advanced-3', () => {
    const a = terms(3, -2, 12);
    const b = a.slice(0, 11).map((value, index) => value * a[index + 1]);
    expectAnswers('seq-geometric-advanced-3', [b[0], commonRatio(b), sum(b.slice(0, 4))]);
  });

  it('seq-geometric-advanced-4', () => {
    const a = terms(2, 3, 20);
    const c = a.slice(0, 19).map((value, index) => value + a[index + 1]);
    const n = c.findIndex((value) => Math.abs(value - 1944) < 1e-9) + 1;
    expect(n).toBeGreaterThan(0);
    expectAnswers('seq-geometric-advanced-4', [c[0], commonRatio(c), n]);
  });

  it('seq-geometric-advanced-5', () => {
    const S = (n: number) => 5 * (3 ** n - 1);
    const a = Array.from({ length: 10 }, (_, index) => (index === 0 ? S(1) : S(index + 1) - S(index)));
    commonRatio(a);
    expectAnswers('seq-geometric-advanced-5', [a[0], a[1], a[4]]);
  });

  it('seq-geometric-advanced-6', () => {
    const profits: number[] = [];
    let profit = 250;
    for (let year = 1; year <= 20; year += 1) {
      profits.push(profit);
      profit *= 1.2;
    }
    const firstYear = profits.findIndex((value) => value > 500) + 1;
    expectAnswers('seq-geometric-advanced-6', [firstYear, sum(profits.slice(0, 4))]);
  });

  it('seq-geometric-advanced-7', () => {
    // Sanity check of the identity of part א at several (a1, q).
    for (const [a1, q] of [[2, 3], [-1.5, 0.4], [5, -2], [0.7, -0.3]]) {
      expect(sum(terms(a1, q, 6))).toBeCloseTo(sum(terms(a1, q, 3)) * (1 + q ** 3), 9);
    }
    const qs = findRoots((q) => sum(terms(2, q, 6)) - 9 * sum(terms(2, q, 3)), -10, 10);
    expect(qs).toHaveLength(1);
    expectAnswers('seq-geometric-advanced-7', [qs[0], sum(terms(2, qs[0], 6))]);
  });

  it('seq-geometric-advanced-8', () => {
    const a1Of = (q: number) => 35 / sum(terms(1, q, 3));
    const qs = rootsAwayFromZero((q) => {
      const t = terms(a1Of(q), q, 3);
      return t[0] * t[1] * t[2] - 1000;
    }, -10, 10);
    expect(qs).toHaveLength(2);
    const increasing = qs.filter((q) => isIncreasing(terms(a1Of(q), q, 8)));
    expect(increasing).toHaveLength(1);
    const q = increasing[0];
    const a = terms(a1Of(q), q, 6);
    expect(sum(a.slice(0, 3))).toBeCloseTo(35, 9);
    const b = a.slice(0, 5).map((value, index) => value * a[index + 1]);
    expectAnswers('seq-geometric-advanced-8', [a[0], q, sum(b)], 7);
  });

  // ───────────── seq-infinite ─────────────
  it('seq-infinite-1', () => {
    const q = commonRatio([24, 12, 6, 3]);
    expectAnswers('seq-infinite-1', [infiniteSum(24, q)]);
  });

  it('seq-infinite-2', () => {
    const q = commonRatio([27, -18, 12, -8]);
    expect(Math.abs(q)).toBeLessThan(1);
    // Part ב: the partial sums of 2 + 6 + 18 + … grow without bound.
    expect(sum(terms(2, commonRatio([2, 6, 18]), 30))).toBeGreaterThan(1e12);
    expectAnswers('seq-infinite-2', [infiniteSum(27, q)]);
  });

  it('seq-infinite-3', () => {
    const qs = findRoots((q) => infiniteSum(12, q) - 36, -0.95, 0.95, 1000);
    expect(qs).toHaveLength(1);
    expectAnswers('seq-infinite-3', [qs[0], terms(12, qs[0], 4)[3]]);
  });

  it('seq-infinite-4', () => {
    const a1Of = (q: number) => 2 / terms(1, q, 2)[1];
    const qs = rootsAwayFromZero((q) => infiniteSum(a1Of(q), q) - 9, -0.95, 0.95, 1000);
    expect(qs).toHaveLength(2);
    const [qSmall, qLarge] = qs;
    for (const q of qs) expect(terms(a1Of(q), q, 2)[1]).toBeCloseTo(2, 9);
    expectAnswers('seq-infinite-4', [a1Of(qSmall), a1Of(qLarge)]);
  });

  it('seq-infinite-5', () => {
    const a1Of = (q: number) => 15 / sum(terms(1, q, 2));
    const qs = findRoots((q) => infiniteSum(a1Of(q), q) - 20, -0.95, 0.95, 1000);
    expect(qs).toHaveLength(2);
    const [qNegative, qPositive] = qs;
    for (const q of qs) expect(sum(terms(a1Of(q), q, 2))).toBeCloseTo(15, 9);
    expectAnswers('seq-infinite-5', [a1Of(qPositive), a1Of(qNegative)]);
  });

  it('seq-infinite-6', () => {
    const a1Of = (q: number) => 12 / infiniteSum(1, q);
    const qs = findRoots((q) => sum(oddPlaces(terms(a1Of(q), q, LONG))) - 9, -0.95, 0.95, 1000);
    expect(qs).toHaveLength(1);
    const q = qs[0];
    const t = terms(a1Of(q), q, LONG);
    expect(sum(t)).toBeCloseTo(12, 9);
    expectAnswers('seq-infinite-6', [q, t[0], sum(evenPlaces(t))]);
  });

  it('seq-infinite-7', () => {
    let height = 12;
    let distance = 12;
    let firstLow = 0;
    for (let bounce = 1; bounce <= LONG; bounce += 1) {
      height *= 0.75;
      distance += 2 * height;
      if (firstLow === 0 && height < 4) firstLow = bounce;
    }
    expectAnswers('seq-infinite-7', [firstLow, distance]);
  });

  it('seq-infinite-8', () => {
    const S = (x: number) => infiniteSum(1, (x - 1) / 2);
    const xs = findRoots((x) => S(x) - 4 / 3, -0.9, 2.9, 1000);
    expect(xs).toHaveLength(1);
    // Part ג: no x in the convergence range gives the sum 1/2 …
    expect(findRoots((x) => S(x) - 0.5, -0.98, 2.98, 1000)).toHaveLength(0);
    // … and at x = -1 (q = -1) the partial sums oscillate between 1 and 0 instead of converging.
    expect(sum(terms(1, -1, 1001))).toBe(1);
    expect(sum(terms(1, -1, 1000))).toBe(0);
    expectAnswers('seq-infinite-8', [xs[0]]);
  });

  // ───────────── seq-recursion ─────────────
  it('seq-recursion-1', () => {
    const a = iterate(5, (value) => 2 * value, 8);
    expect(a.slice(0, 4)).toEqual([5, 10, 20, 40]);
    expectAnswers('seq-recursion-1', [a[7]]);
  });

  it('seq-recursion-2', () => {
    const formula = Array.from({ length: 10 }, (_, index) => 3 * 4 ** (index + 1));
    const q = commonRatio(formula);
    const recursion = iterate(formula[0], (value) => q * value, 10);
    recursion.forEach((value, index) => expect(value).toBeCloseTo(formula[index], 6));
    expectAnswers('seq-recursion-2', [formula[0], q]);
  });

  it('seq-recursion-3', () => {
    const next = (value: number) => value / 3;
    for (const value of [405, 7, -2.5]) expect(3 * next(value) - value).toBeCloseTo(0, 12);
    const a = iterate(405, next, 5);
    expectAnswers('seq-recursion-3', [commonRatio(a), a[4], sum(a)]);
  });

  it('seq-recursion-4', () => {
    const rule = (value: number) => -2 * value;
    const a1 = 40 / iterate(1, rule, 4)[3];
    const a = iterate(a1, rule, 30);
    expect(a[3]).toBe(40);
    const n = a.findIndex((value) => value > 1000) + 1;
    expectAnswers('seq-recursion-4', [a1, n]);
  });

  it('seq-recursion-5', () => {
    const a = Array.from({ length: LONG }, (_, index) => 81 / 3 ** (index + 1));
    commonRatio(a.slice(0, 20));
    expectAnswers('seq-recursion-5', [a[0], sum(a)]);
  });

  it('seq-recursion-6', () => {
    const ks = findRoots((k) => iterate(18, (value) => (k / 3) * value, 3)[2] - 8, -10, 10);
    expect(ks).toHaveLength(2);
    const [kNegative, kPositive] = ks;
    expect(kPositive).toBeCloseTo(2, 9);
    expectAnswers('seq-recursion-6', [sum(iterate(18, (value) => (kPositive / 3) * value, LONG)), sum(iterate(18, (value) => (kNegative / 3) * value, LONG))]);
  });

  it('seq-recursion-7', () => {
    const qs = findRoots((q) => sum(iterate(2, (value) => q * value, 3)) - 26, -10, 10);
    expect(qs).toHaveLength(2);
    const [qNegative, qPositive] = qs;
    expect(qPositive).toBeCloseTo(3, 9);
    expectAnswers('seq-recursion-7', [sum(iterate(2, (value) => qPositive * value, 5)), sum(iterate(2, (value) => qNegative * value, 5))]);
  });

  it('seq-recursion-8', () => {
    // Hour-by-hour simulation: 20% of the amount is broken down every hour.
    const first: number[] = [];
    let amount = 500;
    for (let hour = 1; hour <= 30; hour += 1) {
      amount -= 0.2 * amount;
      first.push(amount);
    }
    const second = Array.from({ length: 30 }, (_, index) => 3200 * 0.5 ** (index + 1));
    expect(commonRatio(second)).toBeCloseTo(0.5, 12);
    const below300 = first.findIndex((value) => value < 300) + 1;
    const crossing = first.findIndex((value, index) => second[index] < value) + 1;
    expectAnswers('seq-recursion-8', [first[0], below300, crossing]);
  });

  // ───────────── seq-advanced-practice ─────────────
  it('seq-advanced-practice-1', () => {
    const a1Of = (q: number) => {
      const t = terms(1, q, 3);
      return 9 / (t[2] - t[0]);
    };
    const qs = findRoots((q) => sum(terms(a1Of(q), q, 4)) - 5 * sum(terms(a1Of(q), q, 2)), 1.01, 10);
    expect(qs).toHaveLength(1);
    const q = qs[0];
    const a1 = a1Of(q);
    const n = firstIndex((k) => sum(terms(a1, q, k)) > 3000);
    expect(sum(terms(a1, q, n - 1))).toBeLessThanOrEqual(3000);
    expectAnswers('seq-advanced-practice-1', [q, a1, n]);
  });

  it('seq-advanced-practice-2', () => {
    const a = terms(48, 0.5, LONG + 1);
    const b = a.slice(0, LONG).map((value, index) => value - a[index + 1]);
    const ratio = commonRatio(b.slice(0, 30));
    for (const n of [1, 4, 6, 11]) expect(sum(b.slice(0, n))).toBeCloseTo(a[0] - a[n], 10);
    expectAnswers('seq-advanced-practice-2', [b[0], ratio, sum(b.slice(0, 6)), sum(b)]);
  });

  it('seq-advanced-practice-3', () => {
    const xs = geometricTripleRoots((x) => 2 * x, (x) => x + 3, (x) => x - 1, -50, 50);
    expect(xs).toHaveLength(2);
    const convergent = xs.filter((x) => Math.abs((x + 3) / (2 * x)) < 1);
    expect(convergent).toHaveLength(1);
    const x = convergent[0];
    const t = terms(2 * x, (x + 3) / (2 * x), LONG);
    expect(t[2]).toBeCloseTo(x - 1, 9);
    expectAnswers('seq-advanced-practice-3', [x, sum(t), sum(t.slice(3))]);
  });

  it('seq-advanced-practice-4', () => {
    const a1Of = (q: number) => 14 / sum(terms(1, q, 3));
    const qs = findRoots((q) => {
      const t = terms(a1Of(q), q, LONG);
      return sum(t) - 3 * sum(evenPlaces(t));
    }, 0.01, 0.95, 1000);
    expect(qs).toHaveLength(1);
    const q = qs[0];
    const t = terms(a1Of(q), q, LONG);
    expect(sum(t.slice(0, 3))).toBeCloseTo(14, 9);
    expectAnswers('seq-advanced-practice-4', [q, t[0], sum(t.map((value) => value * value))]);
  });

  it('seq-advanced-practice-5', () => {
    const growths: number[] = [];
    const heights: number[] = [];
    let height = 0.5;
    let growth = 1;
    for (let year = 1; year <= LONG; year += 1) {
      growths.push(growth);
      height += growth;
      heights.push(height);
      growth *= 0.8;
    }
    expect(heights.every((value) => value < 6)).toBe(true);
    expect(heights[LONG - 1]).toBeLessThan(5.5 + 1e-9);
    expectAnswers('seq-advanced-practice-5', [growths[3], heights[4], heights.findIndex((value) => value > 5) + 1]);
  });

  it('seq-advanced-practice-6', () => {
    // Part א at several finite sequences: S / T = a1 · an.
    for (const [a1, q, n] of [[2, 3, 5], [-1.5, 0.4, 7], [5, -2, 6], [0.3, 1.7, 9]]) {
      const t = terms(a1, q, n);
      const S = sum(t);
      const T = sum(t.map((value) => 1 / value));
      expect(S / T).toBeCloseTo(t[0] * t[n - 1], 8);
    }
    const qs = rootsAwayFromZero((q) => {
      const t = terms(3, q, 6);
      return t[0] * t[5] - 288;
    }, -10, 10);
    expect(qs).toHaveLength(1);
    const t = terms(3, qs[0], 6);
    expect(sum(t)).toBeCloseTo(189, 8);
    expectAnswers('seq-advanced-practice-6', [sum(t.map((value) => 1 / value)), qs[0]]);
  });

  // ───────────── seq-review-a ─────────────
  it('seq-review-a-1', () => {
    const a1Of = (q: number) => 12 / terms(1, q, 2)[1];
    const qs = rootsAwayFromZero((q) => terms(a1Of(q), q, 5)[4] - 324, -10, 10);
    expect(qs).toHaveLength(1);
    const q = qs[0];
    const t = terms(a1Of(q), q, 20);
    const n = t.findIndex((value) => Math.abs(value - 2916) < 1e-6) + 1;
    expect(n).toBeGreaterThan(0);
    expectAnswers('seq-review-a-1', [t[0], q, sum(t.slice(0, 6)), n]);
  });

  it('seq-review-a-2', () => {
    const a1Of = (q: number) => 24 / sum(terms(1, q, 2));
    const qs = findRoots((q) => infiniteSum(a1Of(q), q) - 27, -0.95, 0.95, 1000);
    expect(qs).toHaveLength(2);
    const alternating = qs.filter((q) => q < 0);
    expect(alternating).toHaveLength(1);
    const q = alternating[0];
    const t = terms(a1Of(q), q, LONG);
    expect(t[0] + t[1]).toBeCloseTo(24, 9);
    expectAnswers('seq-review-a-2', [t[0], q, sum(oddPlaces(t))]);
  });

  it('seq-review-a-3', () => {
    const a = iterate(3, (value) => 2 * value, 20);
    const b = a.map((value) => value * value);
    expect(commonRatio(b)).toBeCloseTo(4, 12);
    const k = firstIndex((m) => sum(b.slice(0, m)) >= 3069);
    expect(sum(b.slice(0, k))).toBe(3069);
    expectAnswers('seq-review-a-3', [k]);
  });

  it('seq-review-a-4', () => {
    const xs = geometricTripleRoots((x) => 2 * x - 7, (x) => x + 4, (x) => 3 * x + 2, -50, 50);
    expect(xs).toHaveLength(2);
    const models = xs.map((x) => ({ x, a1: 2 * x - 7, q: (x + 4) / (2 * x - 7) }));
    const convergent = models.filter((model) => Math.abs(model.q) < 1);
    const divergent = models.filter((model) => Math.abs(model.q) > 1);
    expect(convergent).toHaveLength(1);
    expect(divergent).toHaveLength(1);
    expectAnswers('seq-review-a-4', [infiniteSum(convergent[0].a1, convergent[0].q), sum(terms(divergent[0].a1, divergent[0].q, 6))]);
  });

  it('seq-review-a-5', () => {
    const first: number[] = [];
    const second: number[] = [];
    let value1 = 100000;
    let value2 = 80000;
    for (let year = 1; year <= 20; year += 1) {
      value1 -= 0.2 * value1;
      value2 -= 0.1 * value2;
      first.push(value1);
      second.push(value2);
    }
    const below = first.findIndex((value) => value < 40000) + 1;
    const overtake = first.findIndex((value, index) => second[index] > value) + 1;
    expectAnswers('seq-review-a-5', [first[2], below, overtake]);
  });

  it('seq-review-a-6', () => {
    const S = (n: number) => 4 ** n - 1;
    const a = Array.from({ length: 12 }, (_, index) => (index === 0 ? S(1) : S(index + 1) - S(index)));
    const q = commonRatio(a);
    const n = firstIndex((k) => sum(a.slice(0, k)) >= 1023);
    expect(sum(a.slice(0, n))).toBe(1023);
    expectAnswers('seq-review-a-6', [a[0], q, sum(a.slice(3, 6)), n]);
  });

  // ───────────── seq-review-b ─────────────
  it('seq-review-b-1', () => {
    // a1² · q⁴ = 256 gives a1 = ±16 / q²; search both signs and every q, keep the increasing sequence.
    const candidates: Array<{ a1: number; q: number }> = [];
    for (const sign of [1, -1]) {
      const a1Of = (q: number) => (sign * 16) / Math.sqrt(terms(1, q, 5)[4]);
      for (const q of rootsAwayFromZero((r) => {
        const t = terms(a1Of(r), r, 5);
        return t[0] + t[4] - 257;
      }, -20, 20)) {
        candidates.push({ a1: a1Of(q), q });
      }
    }
    const increasing = candidates.filter(({ a1, q }) => isIncreasing(terms(a1, q, 10)));
    expect(increasing).toHaveLength(1);
    const { a1, q } = increasing[0];
    const t = terms(a1, q, 10);
    expect(t[1] * t[3]).toBeCloseTo(256, 8);
    const n = firstIndex((k) => sum(terms(a1, q, k)) >= 1365 - 1e-6);
    expect(sum(terms(a1, q, n))).toBeCloseTo(1365, 6);
    expectAnswers('seq-review-b-1', [t[2], a1, q, n]);
  });

  it('seq-review-b-2', () => {
    // Dose-by-dose simulation: a quarter of the drug remains after 12 hours, then a new 200 mg dose.
    const afterDose: number[] = [];
    let amount = 0;
    for (let dose = 1; dose <= LONG; dose += 1) {
      amount = amount * 0.25 + 200;
      afterDose.push(amount);
    }
    expect(afterDose.every((value) => value < 270)).toBe(true);
    expectAnswers('seq-review-b-2', [afterDose[3], afterDose.findIndex((value) => value > 266) + 1]);
  });

  it('seq-review-b-3', () => {
    const a1Of = (q: number) => 6 / infiniteSum(1, q);
    const qs = findRoots((q) => sum(terms(a1Of(q), q, LONG).map((value) => value * value)) - 12, -0.95, 0.95, 1000);
    expect(qs).toHaveLength(1);
    const q = qs[0];
    const a = terms(a1Of(q), q, LONG + 1);
    const c = a.slice(0, LONG).map((value, index) => value * a[index + 1]);
    expect(commonRatio(c.slice(0, 30))).toBeCloseTo(q * q, 9);
    expectAnswers('seq-review-b-3', [a[0], q, sum(c)]);
  });

  it('seq-review-b-4', () => {
    const qs = findRoots((q) => {
      const t = terms(1, q, LONG);
      return t[0] - 3 * sum(t.slice(1));
    }, 0.01, 0.95, 1000);
    expect(qs).toHaveLength(1);
    const q = qs[0];
    const unit = terms(1, q, 3);
    const a1 = 15 / (unit[1] + unit[2]);
    const t = terms(a1, q, LONG);
    for (const n of [0, 1, 5]) expect(t[n]).toBeCloseTo(3 * sum(t.slice(n + 1)), 9);
    expectAnswers('seq-review-b-4', [q, a1, sum(t)]);
  });

  it('seq-review-b-5', () => {
    const found: Array<{ n: number; q: number }> = [];
    for (let n = 1; n <= 20; n += 1) {
      for (const q of rootsAwayFromZero((r) => sum(terms(1, r, n)) - 31, -20, 20)) {
        if (Math.abs(sum(terms(1, q, 2 * n).slice(n)) - 992) < 1e-6) found.push({ n, q });
      }
    }
    expect(found).toHaveLength(1);
    const { n, q } = found[0];
    expectAnswers('seq-review-b-5', [terms(1, q, n + 1)[n], q, 2 * n]);
  });

  it('seq-review-b-6', () => {
    const a1Of = (q: number) => 18 / infiniteSum(1, q);
    const cOf = (q: number) => {
      const a = terms(a1Of(q), q, LONG + 1);
      return a.slice(0, LONG).map((value, index) => value + a[index + 1]);
    };
    const qs = findRoots((q) => sum(cOf(q)) - 30, 0.01, 0.95, 1000);
    expect(qs).toHaveLength(1);
    const q = qs[0];
    const c = cOf(q);
    expect(commonRatio(c.slice(0, 30))).toBeCloseTo(q, 9);
    const n = c.findIndex((value) => Math.abs(value - 160 / 81) < 1e-8) + 1;
    expect(n).toBeGreaterThan(0);
    expectAnswers('seq-review-b-6', [q, a1Of(q), n]);
  });

  it('every exercise with numeric answers is verified above', () => {
    const verified = new Set(
      [
        ...['intro', 'sum'].flatMap((part) => Array.from({ length: 8 }, (_, i) => `seq-geometric-${part}-${i + 1}`)),
        ...Array.from({ length: 6 }, (_, i) => `seq-geometric-review-${i + 1}`),
        ...Array.from({ length: 8 }, (_, i) => `seq-geometric-advanced-${i + 1}`),
        ...Array.from({ length: 8 }, (_, i) => `seq-infinite-${i + 1}`),
        ...Array.from({ length: 8 }, (_, i) => `seq-recursion-${i + 1}`),
        ...Array.from({ length: 6 }, (_, i) => `seq-advanced-practice-${i + 1}`),
        ...Array.from({ length: 6 }, (_, i) => `seq-review-a-${i + 1}`),
        ...Array.from({ length: 6 }, (_, i) => `seq-review-b-${i + 1}`),
      ],
    );
    for (const exercise of Object.values(sequencesContent).flatMap((lesson) => lesson.exercises)) {
      if (exercise.answers?.length) expect(verified.has(exercise.id), exercise.id).toBe(true);
    }
  });
});
