/**
 * Independent numeric verification of 35581 slot 2 (geometric sequences).
 * Every numericAnswer is recomputed by literally generating the sequence terms in a loop (repeated multiplication,
 * recursion rules, coordinate models) and summing them — never by evaluating the closed-form sum formulas used in the
 * solutions. Infinite sums are approximated by long truncations (|q| <= 1/2 here, so 400 terms are far below 1e-10).
 * Parameters that the solution finds by solving a quadratic are found here with findRoots on the defining condition.
 */
import { describe, expect, it } from 'vitest';
import { findRoots } from '../verify';
import { slot2Problems } from './slot2';

function answer(sectionId: string): number {
  for (const problem of slot2Problems) {
    const section = problem.sections.find((item) => item.id === sectionId);
    if (section) {
      if (section.numericAnswer === undefined) throw new Error(`${sectionId} has no numericAnswer`);
      return section.numericAnswer;
    }
  }
  throw new Error(`Unknown section ${sectionId}`);
}

function expectAnswer(sectionId: string, computed: number, digits = 8) {
  expect(answer(sectionId)).toBeCloseTo(computed, digits);
}

/** The first n terms of the geometric sequence a1, a1·q, a1·q², … generated by repeated multiplication. */
function terms(a1: number, q: number, n: number): number[] {
  const out: number[] = [];
  let current = a1;
  for (let i = 0; i < n; i += 1) {
    out.push(current);
    current *= q;
  }
  return out;
}

function sum(values: number[]): number {
  return values.reduce((total, value) => total + value, 0);
}

/** Truncated infinite sum (400 terms); accurate far beyond 1e-10 for |q| <= 0.75. */
function infiniteSum(a1: number, q: number): number {
  return sum(terms(a1, q, 400));
}

/** Ratios of consecutive terms (to assert that a derived sequence is geometric). */
function ratios(values: number[]): number[] {
  return values.slice(1).map((value, index) => value / values[index]);
}

function expectGeometric(values: number[], q: number) {
  for (const ratio of ratios(values)) expect(ratio).toBeCloseTo(q, 10);
}

describe('35581 slot 2 structure', () => {
  it('has bagrut-style problems with 3–4 sections, 2–3 hints, 3–8 steps and ordered labels', () => {
    expect(slot2Problems.length).toBeGreaterThanOrEqual(3);
    for (const problem of slot2Problems) {
      expect(problem.slot).toBe(2);
      expect(problem.questionnaire).toBe('35581');
      expect(problem.topicId).toBe('sequences');
      expect(problem.subtopicIds).toEqual(['seq-geometric']);
      expect(problem.sections.length).toBeGreaterThanOrEqual(3);
      expect(problem.sections.length).toBeLessThanOrEqual(4);
      expect(problem.estimatedMinutes).toBeGreaterThanOrEqual(15);
      expect(problem.estimatedMinutes).toBeLessThanOrEqual(40);
      expect(problem.sections.map((section) => section.label)).toEqual(['א', 'ב', 'ג', 'ד'].slice(0, problem.sections.length));
      problem.sections.forEach((section, index) => {
        expect(section.id).toBe(`${problem.id}-${'abcd'[index]}`);
        expect(section.hints.length).toBeGreaterThanOrEqual(2);
        expect(section.hints.length).toBeLessThanOrEqual(3);
        expect(section.solutionSteps.length).toBeGreaterThanOrEqual(3);
        expect(section.solutionSteps.length).toBeLessThanOrEqual(8);
      });
    }
    const difficulties = slot2Problems.map((problem) => problem.difficulty);
    expect(Math.min(...difficulties)).toBeGreaterThanOrEqual(2);
    expect(Math.max(...difficulties)).toBe(3);
    expect(difficulties.filter((d) => d === 3).length * 3).toBeGreaterThanOrEqual(difficulties.length);
  });

  it('has unique ids and no backticks or template interpolation inside the texts', () => {
    const ids = slot2Problems.flatMap((problem) => [problem.id, ...problem.sections.map((section) => section.id)]);
    expect(new Set(ids).size).toBe(ids.length);
    for (const problem of slot2Problems) {
      for (const section of problem.sections) {
        for (const text of [section.statement, ...section.hints, ...section.solutionSteps, section.finalAnswer]) {
          expect(text).not.toContain('`');
          expect(text).not.toContain('${');
          expect((text.match(/\$/g) ?? []).length % 2).toBe(0);
        }
      }
    }
  });
});

describe('35581-2-1 – a4 − a2 = 48, a3 − a1 = 16', () => {
  const a = terms(2, 3, 20);
  it('model satisfies the givens and q is the unique solution of the system', () => {
    expect(a[3] - a[1]).toBe(48);
    expect(a[2] - a[0]).toBe(16);
    // a1 is forced by the second given: a1 = 16 / (q² − 1); the first given then becomes an equation in q alone.
    const condition = (q: number) => (16 / (q * q - 1)) * q * (q * q - 1) - 48;
    const roots = findRoots(condition, -6, 6).filter((q) => Math.abs(Math.abs(q) - 1) > 1e-6);
    expect(roots).toHaveLength(1);
    expect(roots[0]).toBeCloseTo(3, 8);
  });
  it('35581-2-1-b', () => expectAnswer('35581-2-1-b', sum(a.slice(0, 8))));
  it('35581-2-1-c', () => {
    const index = a.findIndex((term) => term > 10000);
    expect(a[index - 1]).toBeLessThan(10000);
    expectAnswer('35581-2-1-c', index + 1);
  });
  it('35581-2-1-d', () => {
    let running = 0;
    let found = 0;
    for (let n = 1; n <= a.length; n += 1) {
      running += a[n - 1];
      if (running === 59048) found = n;
    }
    expect(found).toBeGreaterThan(0);
    expectAnswer('35581-2-1-d', found);
  });
});

describe('35581-2-2 – infinite sum 12, sum of squares 72', () => {
  const a = terms(8, 1 / 3, 400);
  it('model satisfies the givens and q is the unique solution', () => {
    expect(sum(a)).toBeCloseTo(12, 10);
    expect(sum(a.map((term) => term * term))).toBeCloseTo(72, 10);
    // With a1 = 12(1 − q) forced by the first given, the squares condition is an equation in q alone on (−1, 1).
    const condition = (q: number) => sum(terms(12 * (1 - q), q, 400).map((term) => term * term)) - 72;
    const roots = findRoots(condition, -0.95, 0.95, 400);
    expect(roots).toHaveLength(1);
    expect(roots[0]).toBeCloseTo(1 / 3, 8);
  });
  it('35581-2-2-b', () => expectAnswer('35581-2-2-b', sum(a.filter((_, index) => index % 2 === 0))));
  it('35581-2-2-c', () => expectAnswer('35581-2-2-c', sum(a.map((term, index) => (index % 2 === 0 ? term : -term)))));
  it('35581-2-2-d', () => {
    const c = a.slice(0, -1).map((term, index) => term - a[index + 1]);
    expectGeometric(c.slice(0, 40), 1 / 3);
    expect(c[0]).toBeCloseTo(16 / 3, 12);
    expectAnswer('35581-2-2-d', sum(c));
  });
});

describe('35581-2-3 – recursion a(n+1) = 1.5·a(n), a1 = 16', () => {
  const a: number[] = [16];
  for (let n = 1; n < 30; n += 1) a.push(1.5 * a[n - 1]);
  const b = a.slice(0, -1).map((term, index) => term + a[index + 1]);
  it('35581-2-3-a', () => {
    expectGeometric(a, 1.5);
    expectAnswer('35581-2-3-a', a[4]);
  });
  it('35581-2-3-b (b is geometric with b1 = 40, ratio 3/2)', () => {
    expectGeometric(b, 1.5);
    expect(b[0]).toBe(40);
    for (let n = 0; n < b.length - 1; n += 1) expect(b[n + 1]).toBeCloseTo(1.5 * b[n], 10);
  });
  it('35581-2-3-c', () => {
    const index = b.findIndex((term) => Math.abs(term - 303.75) < 1e-9);
    expect(index).toBeGreaterThanOrEqual(0);
    expectAnswer('35581-2-3-c', index + 1);
  });
  it('35581-2-3-d', () => {
    for (const n of [1, 2, 5, 9, 15]) expect(sum(b.slice(0, n))).toBeCloseTo(2.5 * sum(a.slice(0, n)), 8);
    expectAnswer('35581-2-3-d', sum(b.slice(0, 6)));
  });
});

describe('35581-2-4 – three numbers inserted between 3 and 48', () => {
  it('35581-2-4-a: exactly two ratios make 3, ?, ?, ?, 48 geometric', () => {
    const fifth = (q: number) => terms(3, q, 5)[4] - 48;
    const roots = findRoots(fifth, -4, 4);
    expect(roots).toHaveLength(2);
    expect(roots[0]).toBeCloseTo(-2, 8);
    expect(roots[1]).toBeCloseTo(2, 8);
    expect(terms(3, 2, 5)).toEqual([3, 6, 12, 24, 48]);
    expect(terms(3, -2, 5)).toEqual([3, -6, 12, -24, 48]);
  });
  const a = terms(3, 2, 60);
  const c = a.slice(0, -1).map((term, index) => term * a[index + 1]);
  it('35581-2-4-b', () => {
    expect(c[0]).toBe(18);
    expectGeometric(c, 4);
    expectAnswer('35581-2-4-b', c[1] / c[0]);
  });
  it('35581-2-4-c', () => expectAnswer('35581-2-4-c', sum(c.slice(0, 5))));
  it('35581-2-4-d', () => {
    const d = c.map((term) => 1 / term);
    expectGeometric(d.slice(0, 40), 0.25);
    expectAnswer('35581-2-4-d', sum(d), 10);
  });
});

describe('35581-2-5 – 3x−1, 8−4x, 11−3x are consecutive geometric terms', () => {
  const triple = (x: number) => [3 * x - 1, 8 - 4 * x, 11 - 3 * x];
  const roots = findRoots((x) => triple(x)[1] ** 2 - triple(x)[0] * triple(x)[2], -10, 10);
  it('35581-2-5-a: both roots of the middle-term condition give valid geometric triples', () => {
    expect(roots).toHaveLength(2);
    expect(roots[0]).toBeCloseTo(1, 8);
    expect(roots[1]).toBeCloseTo(3, 8);
    for (const x of roots) {
      const [p, q, r] = triple(Math.round(x));
      expect(p !== 0 && q !== 0 && r !== 0).toBe(true);
      expect(q / p).toBeCloseTo(r / q, 10);
    }
    expect(triple(1)).toEqual([2, 4, 8]);
    expect(triple(3)).toEqual([8, -4, 2]);
  });
  it('35581-2-5-b', () => {
    // x = 1 gives ratio 2 (partial sums diverge); x = 3 gives ratio −1/2 (convergent).
    expect(sum(terms(2, 2, 60))).toBeGreaterThan(1e15);
    expectAnswer('35581-2-5-b', infiniteSum(8, -0.5), 10);
  });
  it('35581-2-5-c', () => expectAnswer('35581-2-5-c', sum(terms(2, 2, 10))));
  it('35581-2-5-d', () => {
    const total = infiniteSum(8, -0.5);
    let running = 0;
    let smallest = 0;
    for (let n = 1; n <= 40 && smallest === 0; n += 1) {
      running += terms(8, -0.5, n)[n - 1];
      if (Math.abs(total - running) < 0.01) smallest = n;
    }
    expect(Math.abs(total - sum(terms(8, -0.5, smallest - 1)))).toBeGreaterThan(0.01);
    expectAnswer('35581-2-5-d', smallest);
  });
});

describe('35581-2-6 – bouncing ball, 60% rebound', () => {
  const heights = (ratio: number, n: number): number[] => {
    const out: number[] = [];
    let h = 10;
    for (let i = 0; i < n; i += 1) {
      h *= ratio;
      out.push(h);
    }
    return out;
  };
  const totalDistance = (ratio: number) => 10 + 2 * sum(heights(ratio, 2000));
  const h = heights(0.6, 400);
  it('35581-2-6-a', () => {
    expectGeometric(h.slice(0, 50), 0.6);
    expect(h[0]).toBeCloseTo(6, 12);
    expectAnswer('35581-2-6-a', h[2]);
  });
  it('35581-2-6-b', () => expectAnswer('35581-2-6-b', totalDistance(0.6), 10));
  it('35581-2-6-c', () => {
    const index = h.findIndex((height) => height < 1);
    expect(h[index - 1]).toBeGreaterThan(1);
    expectAnswer('35581-2-6-c', index + 1);
  });
  it('35581-2-6-d', () => {
    const roots = findRoots((r) => totalDistance(r) - 30, 0.01, 0.95, 500);
    expect(roots).toHaveLength(1);
    expectAnswer('35581-2-6-d', 100 * roots[0], 7);
  });
});

describe('35581-2-7 – S4 = 10·S2, S2 = 8', () => {
  const partial = (a1: number, q: number, n: number) => sum(terms(a1, q, n));
  it('35581-2-7-a (S2n = Sn(1 + q^n) on sample sequences)', () => {
    for (const [a1, q] of [[2, 3], [-1.5, 0.4], [5, -2]]) {
      for (const n of [1, 2, 3, 5]) expect(partial(a1, q, 2 * n)).toBeCloseTo(partial(a1, q, n) * (1 + q ** n), 6);
    }
  });
  it('35581-2-7-b: exactly q = ±3 (with a1 = 8 / (1 + q))', () => {
    const condition = (q: number) => partial(8 / (1 + q), q, 4) - 80;
    const roots = findRoots(condition, -6, 6).filter((q) => Math.abs(q + 1) > 1e-3);
    expect(roots).toHaveLength(2);
    expect(roots[0]).toBeCloseTo(-3, 8);
    expect(roots[1]).toBeCloseTo(3, 8);
    for (const [a1, q] of [[2, 3], [-4, -3]]) {
      expect(partial(a1, q, 2)).toBe(8);
      expect(partial(a1, q, 4)).toBe(80);
    }
  });
  it('35581-2-7-c (identity on sample sequences)', () => {
    for (const [a1, q] of [[2, 3], [1.3, -0.7], [-4, 0.5]]) {
      for (const n of [1, 2, 3]) {
        const left = (partial(a1, q, 2 * n) - partial(a1, q, n)) ** 2;
        const right = partial(a1, q, n) * (partial(a1, q, 3 * n) - partial(a1, q, 2 * n));
        expect(left).toBeCloseTo(right, 6);
      }
    }
  });
  it('35581-2-7-d', () => {
    expect(partial(-4, -3, 6)).toBe(partial(2, 3, 6));
    expectAnswer('35581-2-7-d', partial(2, 3, 6));
  });
});

describe('35581-2-8 – nested midpoint squares (coordinate model)', () => {
  type Point = [number, number];
  const shoelace = (points: Point[]) =>
    Math.abs(points.reduce((total, [x1, y1], index) => {
      const [x2, y2] = points[(index + 1) % points.length];
      return total + x1 * y2 - x2 * y1;
    }, 0)) / 2;
  const perimeter = (points: Point[]) =>
    points.reduce((total, [x1, y1], index) => {
      const [x2, y2] = points[(index + 1) % points.length];
      return total + Math.hypot(x2 - x1, y2 - y1);
    }, 0);
  const squares: Point[][] = [[[0, 0], [8, 0], [8, 8], [0, 8]]];
  for (let k = 1; k < 200; k += 1) {
    const prev = squares[k - 1];
    squares.push(prev.map(([x, y], index): Point => {
      const [x2, y2] = prev[(index + 1) % 4];
      return [(x + x2) / 2, (y + y2) / 2];
    }));
  }
  const areas = squares.map(shoelace);
  it('model satisfies the givens and the figure has the required SVG frame', () => {
    expect(areas[0]).toBe(64);
    const figure = slot2Problems.find((problem) => problem.id === '35581-2-8')?.figureSvg ?? '';
    expect(figure).toContain('viewBox="0 0 320 240"');
    expect(figure).not.toMatch(/<svg[^>]*\s(width|height)=/);
  });
  it('35581-2-8-a', () => {
    expectGeometric(areas.slice(0, 30), 0.5);
    expectAnswer('35581-2-8-a', areas[5], 10);
  });
  it('35581-2-8-b', () => expectAnswer('35581-2-8-b', sum(areas), 10));
  it('35581-2-8-c', () => expectAnswer('35581-2-8-c', sum(squares.map(perimeter)), 10));
  it('35581-2-8-d', () => {
    const rings = areas.slice(0, -1).map((area, index) => area - areas[index + 1]);
    expectAnswer('35581-2-8-d', sum(rings.filter((_, index) => index % 2 === 0)), 10);
  });
});
